# Generated by Django 4.2.3 on 2023-09-06 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrumapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainheader',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
