# Generated by Django 4.2.3 on 2023-09-06 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrumapp', '0002_mainheader_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainheader',
            name='image_eng',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='mainheader',
            name='image_ru',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
