# Generated by Django 4.2.3 on 2023-09-07 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astrumapp', '0004_remove_ourmentors_button_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locatsia',
            name='image',
        ),
        migrations.RemoveField(
            model_name='locatsia',
            name='image_eng',
        ),
        migrations.RemoveField(
            model_name='locatsia',
            name='image_ru',
        ),
    ]
