# Generated by Django 4.2.3 on 2023-09-07 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astrumapp', '0005_remove_locatsia_image_remove_locatsia_image_eng_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='category1',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='category1_eng',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='category1_ru',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='category2',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='category2_eng',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='category2_ru',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='category3',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='category3_eng',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='category3_ru',
        ),
    ]
