# Generated by Django 4.2.3 on 2023-09-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrumapp', '0008_alter_akademyahaqidaheader_descriptions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assidemashgulotkurslari',
            name='descriptions',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='assidemashgulotkurslari',
            name='descriptions_eng',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='assidemashgulotkurslari',
            name='descriptions_ru',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
