# Generated by Django 4.2.3 on 2023-09-07 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrumapp', '0009_alter_assidemashgulotkurslari_descriptions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karyera',
            name='category',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='karyera',
            name='category_eng',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='karyera',
            name='category_ru',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='karyera',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='karyera',
            name='image_eng',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='karyera',
            name='image_ru',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='karyera',
            name='title',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='karyera',
            name='title_eng',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='karyera',
            name='title_ru',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='kurslar',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='kurslar',
            name='image_eng',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='kurslar',
            name='image_ru',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='kurslar',
            name='title',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='kurslar',
            name='title_eng',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='kurslar',
            name='title_ru',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image_ru',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title_eng',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title_ru',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='vakansiya',
            name='occupation',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='vakansiya',
            name='occupation_eng',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='vakansiya',
            name='occupation_ru',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
