# Generated by Django 4.2.3 on 2023-09-07 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrumapp', '0010_alter_karyera_category_alter_karyera_category_eng_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='karyera',
            old_name='image',
            new_name='image1',
        ),
        migrations.RenameField(
            model_name='karyera',
            old_name='image_eng',
            new_name='image1_eng',
        ),
        migrations.RenameField(
            model_name='karyera',
            old_name='image_ru',
            new_name='image1_ru',
        ),
        migrations.RemoveField(
            model_name='karyera',
            name='category',
        ),
        migrations.RemoveField(
            model_name='karyera',
            name='category_eng',
        ),
        migrations.RemoveField(
            model_name='karyera',
            name='category_ru',
        ),
        migrations.AddField(
            model_name='karyera',
            name='image2',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='karyera',
            name='image2_eng',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='karyera',
            name='image2_ru',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='karyera',
            name='image3',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='karyera',
            name='image3_eng',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='karyera',
            name='image3_ru',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='karyera',
            name='image4',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='karyera',
            name='image4_eng',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='karyera',
            name='image4_ru',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='karyera',
            name='image5',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='karyera',
            name='image5_eng',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='karyera',
            name='image5_ru',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
