# Generated by Django 4.2.3 on 2023-09-07 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrumapp', '0011_rename_image_karyera_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vakansiya',
            name='button_text',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='vakansiya',
            name='button_text_eng',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='vakansiya',
            name='button_text_ru',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
