# Generated by Django 4.2.3 on 2023-09-07 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astrumapp', '0012_vakansiya_button_text_vakansiya_button_text_eng_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='karyera',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='karyera',
            name='image1_eng',
        ),
        migrations.RemoveField(
            model_name='karyera',
            name='image1_ru',
        ),
        migrations.RemoveField(
            model_name='karyera',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='karyera',
            name='image2_eng',
        ),
        migrations.RemoveField(
            model_name='karyera',
            name='image2_ru',
        ),
        migrations.RemoveField(
            model_name='karyera',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='karyera',
            name='image3_eng',
        ),
        migrations.RemoveField(
            model_name='karyera',
            name='image3_ru',
        ),
        migrations.RemoveField(
            model_name='karyera',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='karyera',
            name='image4_eng',
        ),
        migrations.RemoveField(
            model_name='karyera',
            name='image4_ru',
        ),
        migrations.RemoveField(
            model_name='karyera',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='karyera',
            name='image5_eng',
        ),
        migrations.RemoveField(
            model_name='karyera',
            name='image5_ru',
        ),
    ]
