# Generated by Django 4.2.3 on 2023-09-07 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrumapp', '0013_remove_karyera_image1_remove_karyera_image1_eng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vakansiya',
            name='data_eng',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='vakansiya',
            name='image_eng',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='vakansiya',
            name='prise',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='vakansiya',
            name='prise_eng',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='vakansiya',
            name='prise_ru',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
