# Generated by Django 4.2.3 on 2023-09-07 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrumapp', '0014_alter_vakansiya_data_eng_alter_vakansiya_image_eng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vakansiya',
            name='data',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='vakansiya',
            name='data_eng',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='vakansiya',
            name='data_ru',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='vakansiya',
            name='prise',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vakansiya',
            name='prise_eng',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vakansiya',
            name='prise_ru',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
