# Generated by Django 4.2.3 on 2023-09-07 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrumapp', '0015_alter_vakansiya_data_alter_vakansiya_data_eng_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KurslarUchunDarslar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('descriptions', models.CharField(max_length=500)),
                ('image1', models.ImageField(blank=True, upload_to='')),
                ('image2', models.ImageField(blank=True, upload_to='')),
                ('image3', models.ImageField(blank=True, upload_to='')),
                ('image4', models.ImageField(blank=True, upload_to='')),
                ('image5', models.ImageField(blank=True, upload_to='')),
                ('title_ru', models.CharField(blank=True, max_length=100)),
                ('name_ru', models.CharField(max_length=100)),
                ('descriptions_ru', models.CharField(max_length=250)),
                ('image1_ru', models.ImageField(blank=True, upload_to='')),
                ('image2_ru', models.ImageField(blank=True, upload_to='')),
                ('image3_ru', models.ImageField(blank=True, upload_to='')),
                ('image4_ru', models.ImageField(blank=True, upload_to='')),
                ('image5_ru', models.ImageField(blank=True, upload_to='')),
                ('title_eng', models.CharField(blank=True, max_length=100)),
                ('name_eng', models.CharField(max_length=100)),
                ('descriptions_eng', models.CharField(max_length=250)),
                ('image1_eng', models.ImageField(blank=True, upload_to='')),
                ('image2_eng', models.ImageField(blank=True, upload_to='')),
                ('image3_eng', models.ImageField(blank=True, upload_to='')),
                ('image4_eng', models.ImageField(blank=True, upload_to='')),
                ('image5_eng', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='TreningDasturi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=250)),
                ('title_ru', models.CharField(blank=True, max_length=100)),
                ('name_ru', models.CharField(max_length=250)),
                ('title_eng', models.CharField(blank=True, max_length=100)),
                ('name_eng', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='TreningDasturiAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('descriptions', models.CharField(max_length=250)),
                ('title_ru', models.CharField(blank=True, max_length=100)),
                ('descriptions_ru', models.CharField(max_length=250)),
                ('title_eng', models.CharField(blank=True, max_length=100)),
                ('descriptions_eng', models.CharField(max_length=250)),
            ],
        ),
    ]
