# Generated by Django 4.2.3 on 2023-09-07 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrumapp', '0016_kurslaruchundarslar_treningdasturi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kurslaruchundarslar',
            name='descriptions',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='kurslaruchundarslar',
            name='descriptions_eng',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='kurslaruchundarslar',
            name='descriptions_ru',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='kurslaruchundarslar',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='kurslaruchundarslar',
            name='name_eng',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='kurslaruchundarslar',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='treningdasturi',
            name='name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='treningdasturi',
            name='name_eng',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='treningdasturi',
            name='name_ru',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='treningdasturianswer',
            name='descriptions',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='treningdasturianswer',
            name='descriptions_eng',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='treningdasturianswer',
            name='descriptions_ru',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
