# Generated by Django 4.2.3 on 2023-09-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrumapp', '0018_remove_kurslaruchundarslar_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Narxlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=156)),
                ('name', models.CharField(blank=True, max_length=250)),
                ('descriptions', models.CharField(blank=True, max_length=500)),
                ('title_ru', models.CharField(blank=True, max_length=156)),
                ('name_ru', models.CharField(blank=True, max_length=250)),
                ('descriptions_ru', models.CharField(blank=True, max_length=500)),
                ('title_eng', models.CharField(blank=True, max_length=156)),
                ('name_eng', models.CharField(blank=True, max_length=250)),
                ('descriptions_eng', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
