# Generated by Django 4.2.3 on 2023-09-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrumapp', '0019_narxlar'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugungiTolov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oylik_tolov_chegirma', models.CharField(blank=True, max_length=100)),
                ('skidka', models.CharField(blank=True, max_length=100)),
                ('narx_oyiga', models.CharField(blank=True, max_length=100)),
                ('kurs_name', models.CharField(blank=True, max_length=100)),
                ('kurs_narx', models.CharField(blank=True, max_length=100)),
                ('skidka_text', models.CharField(blank=True, max_length=100)),
                ('skidka_narx', models.CharField(blank=True, max_length=100)),
                ('jami_skidka', models.CharField(blank=True, max_length=100)),
                ('jami_narx', models.CharField(blank=True, max_length=100)),
                ('oylik_tolov_chegirma_ru', models.CharField(blank=True, max_length=100)),
                ('skidka_ru', models.CharField(blank=True, max_length=100)),
                ('narx_oyiga_ru', models.CharField(blank=True, max_length=100)),
                ('kurs_name_ru', models.CharField(blank=True, max_length=100)),
                ('kurs_narx_ru', models.CharField(blank=True, max_length=100)),
                ('skidka_text_ru', models.CharField(blank=True, max_length=100)),
                ('skidka_narx_ru', models.CharField(blank=True, max_length=100)),
                ('jami_skidka_ru', models.CharField(blank=True, max_length=100)),
                ('jami_narx_ru', models.CharField(blank=True, max_length=100)),
                ('oylik_tolov_chegirma_eng', models.CharField(blank=True, max_length=100)),
                ('skidka_eng', models.CharField(blank=True, max_length=100)),
                ('narx_oyiga_eng', models.CharField(blank=True, max_length=100)),
                ('kurs_name_eng', models.CharField(blank=True, max_length=100)),
                ('kurs_narx_eng', models.CharField(blank=True, max_length=100)),
                ('skidka_text_eng', models.CharField(blank=True, max_length=100)),
                ('skidka_narx_eng', models.CharField(blank=True, max_length=100)),
                ('jami_skidka_eng', models.CharField(blank=True, max_length=100)),
                ('jami_narx_eng', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BugungiTolovQulayligi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500)),
                ('title_ru', models.CharField(blank=True, max_length=500)),
                ('title_eng', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='OylikTolov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oyiga', models.CharField(blank=True, max_length=100)),
                ('besh_x_oylik_tolovlar', models.CharField(blank=True, max_length=100)),
                ('jami_narx', models.CharField(blank=True, max_length=100)),
                ('oyiga_ru', models.CharField(blank=True, max_length=100)),
                ('besh_x_oylik_tolovlar_ru', models.CharField(blank=True, max_length=100)),
                ('jami_narx_ru', models.CharField(blank=True, max_length=100)),
                ('oyiga_eng', models.CharField(blank=True, max_length=100)),
                ('besh_x_oylik_tolovlar_eng', models.CharField(blank=True, max_length=100)),
                ('jami_narx_eng', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OylikTolovQulayligi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500)),
                ('title_ru', models.CharField(blank=True, max_length=500)),
                ('title_eng', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
