# Generated by Django 4.2.3 on 2023-09-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrumapp', '0020_bugungitolov_bugungitolovqulayligi_oyliktolov_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KursJadvali',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=156)),
                ('name', models.CharField(blank=True, max_length=156)),
                ('descriptions', models.CharField(blank=True, max_length=156)),
            ],
        ),
        migrations.CreateModel(
            name='KursPLan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurs_name', models.CharField(blank=True, max_length=156)),
                ('data', models.CharField(blank=True, max_length=500)),
                ('oqish_davomiligi', models.CharField(blank=True, max_length=156)),
                ('name_lastname', models.CharField(blank=True, max_length=156)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('sohasi', models.CharField(blank=True, max_length=156)),
            ],
        ),
    ]
