# Generated by Django 4.2.3 on 2023-09-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrumapp', '0021_kursjadvali_kursplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Savollar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=156)),
                ('name', models.CharField(blank=True, max_length=156)),
                ('descriptions', models.CharField(blank=True, max_length=156)),
                ('title_ru', models.CharField(blank=True, max_length=156)),
                ('name_ru', models.CharField(blank=True, max_length=156)),
                ('descriptions_ru', models.CharField(blank=True, max_length=156)),
                ('title_eng', models.CharField(blank=True, max_length=156)),
                ('name_eng', models.CharField(blank=True, max_length=156)),
                ('descriptions_eng', models.CharField(blank=True, max_length=156)),
            ],
        ),
        migrations.CreateModel(
            name='SavollarJavob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('descriptions', models.CharField(blank=True, max_length=1000)),
                ('title_ru', models.CharField(blank=True, max_length=200)),
                ('descriptions_ru', models.CharField(blank=True, max_length=1000)),
                ('title_eng', models.CharField(blank=True, max_length=200)),
                ('descriptions_eng', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='kursjadvali',
            name='descriptions_eng',
            field=models.CharField(blank=True, max_length=156),
        ),
        migrations.AddField(
            model_name='kursjadvali',
            name='descriptions_ru',
            field=models.CharField(blank=True, max_length=156),
        ),
        migrations.AddField(
            model_name='kursjadvali',
            name='name_eng',
            field=models.CharField(blank=True, max_length=156),
        ),
        migrations.AddField(
            model_name='kursjadvali',
            name='name_ru',
            field=models.CharField(blank=True, max_length=156),
        ),
        migrations.AddField(
            model_name='kursjadvali',
            name='title_eng',
            field=models.CharField(blank=True, max_length=156),
        ),
        migrations.AddField(
            model_name='kursjadvali',
            name='title_ru',
            field=models.CharField(blank=True, max_length=156),
        ),
        migrations.AddField(
            model_name='kursplan',
            name='data_eng',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='kursplan',
            name='data_ru',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='kursplan',
            name='image_eng',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='kursplan',
            name='image_ru',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='kursplan',
            name='kurs_name_eng',
            field=models.CharField(blank=True, max_length=156),
        ),
        migrations.AddField(
            model_name='kursplan',
            name='kurs_name_ru',
            field=models.CharField(blank=True, max_length=156),
        ),
        migrations.AddField(
            model_name='kursplan',
            name='name_lastname_eng',
            field=models.CharField(blank=True, max_length=156),
        ),
        migrations.AddField(
            model_name='kursplan',
            name='name_lastname_ru',
            field=models.CharField(blank=True, max_length=156),
        ),
        migrations.AddField(
            model_name='kursplan',
            name='oqish_davomiligi_eng',
            field=models.CharField(blank=True, max_length=156),
        ),
        migrations.AddField(
            model_name='kursplan',
            name='oqish_davomiligi_ru',
            field=models.CharField(blank=True, max_length=156),
        ),
        migrations.AddField(
            model_name='kursplan',
            name='sohasi_eng',
            field=models.CharField(blank=True, max_length=156),
        ),
        migrations.AddField(
            model_name='kursplan',
            name='sohasi_ru',
            field=models.CharField(blank=True, max_length=156),
        ),
    ]
