# Generated by Django 4.2.4 on 2023-09-09 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astrumapp', '0022_savollar_savollarjavob_kursjadvali_descriptions_eng_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutUs',
        ),
        migrations.DeleteModel(
            name='MainHeader',
        ),
    ]
