# Generated by Django 4.2.4 on 2023-09-09 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astrumapp', '0024_delete_whyexactlyastrum'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TheRules',
        ),
    ]
