# Generated by Django 4.2.4 on 2023-09-09 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astrumapp', '0025_delete_therules'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsHeader',
        ),
    ]
