# Generated by Django 4.2.4 on 2023-09-09 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astrumapp', '0027_delete_educationcourses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
