# Generated by Django 4.2.4 on 2023-09-09 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astrumapp', '0028_delete_courses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WhyAstrum',
        ),
    ]
