# Generated by Django 4.2.4 on 2023-09-09 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astrumapp', '0029_delete_whyastrum'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WhyAstrumAnswer',
        ),
    ]
