# Generated by Django 4.2.4 on 2023-09-09 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astrumapp', '0030_delete_whyastrumanswer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OurMentors',
        ),
    ]
