# Generated by Django 4.2.4 on 2023-09-09 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astrumapp', '0032_delete_mentors'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Locatsia',
        ),
    ]
