# Generated by Django 4.2.4 on 2023-09-09 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astrumapp', '0033_delete_locatsia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AstrumLocatsia',
        ),
    ]
