# Generated by Django 4.2.4 on 2023-09-09 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astrumapp', '0034_delete_astrumlocatsia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutAcademy',
        ),
        migrations.DeleteModel(
            name='Footer',
        ),
    ]
