# Generated by Django 4.2.3 on 2023-09-10 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astrumapp', '0035_delete_aboutacademy_delete_footer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AkademyaHaqidaHeader',
        ),
        migrations.DeleteModel(
            name='AssideAkademiyaHaqida',
        ),
        migrations.DeleteModel(
            name='AssideKurslar',
        ),
        migrations.DeleteModel(
            name='AssideMashgulotKurslari',
        ),
        migrations.DeleteModel(
            name='AssideOqituvchilar',
        ),
        migrations.DeleteModel(
            name='AssideQulaylik',
        ),
        migrations.DeleteModel(
            name='AssideTalimTizimi',
        ),
    ]
