# Generated by Django 4.2.3 on 2023-09-11 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astrumapp', '0036_delete_akademyahaqidaheader_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Karyera',
        ),
        migrations.DeleteModel(
            name='Kurslar',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.DeleteModel(
            name='Vakansiya',
        ),
    ]
