# Generated by Django 4.2.3 on 2023-09-11 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astrumapp', '0037_delete_karyera_delete_kurslar_delete_photo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BugungiTolov',
        ),
        migrations.DeleteModel(
            name='BugungiTolovQulayligi',
        ),
        migrations.DeleteModel(
            name='KursJadvali',
        ),
        migrations.DeleteModel(
            name='KurslarUchunDarslar',
        ),
        migrations.DeleteModel(
            name='KursPLan',
        ),
        migrations.DeleteModel(
            name='Narxlar',
        ),
        migrations.DeleteModel(
            name='OylikTolov',
        ),
        migrations.DeleteModel(
            name='OylikTolovQulayligi',
        ),
        migrations.DeleteModel(
            name='Savollar',
        ),
        migrations.DeleteModel(
            name='SavollarJavob',
        ),
        migrations.DeleteModel(
            name='TreningDasturi',
        ),
        migrations.DeleteModel(
            name='TreningDasturiAnswer',
        ),
    ]
