# Generated by Django 4.2.2 on 2023-10-05 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('astrumapp', '0038_delete_bugungitolov_delete_bugungitolovqulayligi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('nick_name', models.CharField(max_length=100)),
                ('random_code', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name': 'Report Data',
                'verbose_name_plural': 'Report Data',
            },
        ),
    ]
