# Generated by Django 4.2.2 on 2023-10-05 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astrumapp', '0040_reportdata_created_time_alter_reportdata_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportdata',
            options={'ordering': ('created_time',), 'verbose_name': 'Report Data', 'verbose_name_plural': 'Report Data'},
        ),
    ]
