# Generated by Django 4.2.3 on 2023-09-11 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Foto_suratlar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='image',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='image_eng',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='image_ru',
        ),
    ]
