# Generated by Django 4.2.4 on 2023-09-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('photo_name', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(blank=True, max_length=156)),
                ('descriptions', models.CharField(blank=True, max_length=10000)),
                ('img', models.ImageField(blank=True, upload_to='')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('title_ru', models.CharField(blank=True, max_length=50)),
                ('photo_name_ru', models.CharField(blank=True, max_length=50)),
                ('name_ru', models.CharField(blank=True, max_length=156)),
                ('descriptions_ru', models.CharField(blank=True, max_length=10000)),
                ('title_eng', models.CharField(blank=True, max_length=50)),
                ('photo_name_eng', models.CharField(blank=True, max_length=50)),
                ('name_eng', models.CharField(blank=True, max_length=156)),
                ('descriptions_eng', models.CharField(blank=True, max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='MainHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('title_ru', models.CharField(blank=True, max_length=50)),
                ('title_eng', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
