# Generated by Django 4.2.4 on 2023-09-09 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Asosiy_Sahifa', '0002_whyastrum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whyastrum',
            name='short_descriptions',
        ),
        migrations.RemoveField(
            model_name='whyastrum',
            name='short_descriptions_eng',
        ),
        migrations.RemoveField(
            model_name='whyastrum',
            name='short_descriptions_ru',
        ),
    ]
