# Generated by Django 4.2.4 on 2023-09-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asosiy_Sahifa', '0004_whyastruminfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256)),
                ('link', models.CharField(max_length=255)),
                ('title_ru', models.CharField(blank=True, max_length=256)),
                ('link_ru', models.CharField(max_length=255)),
                ('title_eng', models.CharField(blank=True, max_length=256)),
                ('link_eng', models.CharField(max_length=255)),
            ],
        ),
    ]
