# Generated by Django 4.2.4 on 2023-09-09 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Asosiy_Sahifa', '0006_coursinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursinfo',
            name='button_text',
        ),
        migrations.RemoveField(
            model_name='coursinfo',
            name='button_text_eng',
        ),
        migrations.RemoveField(
            model_name='coursinfo',
            name='button_text_ru',
        ),
    ]
