# Generated by Django 4.2.4 on 2023-09-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asosiy_Sahifa', '0008_whyastrumpart2'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyAstrumInfo2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=156)),
                ('title', models.CharField(blank=True, max_length=156)),
                ('short_descriptions', models.CharField(blank=True, max_length=256)),
                ('name_ru', models.CharField(blank=True, max_length=156)),
                ('title_ru', models.CharField(blank=True, max_length=156)),
                ('short_descriptions_ru', models.CharField(blank=True, max_length=256)),
                ('name_eng', models.CharField(blank=True, max_length=156)),
                ('title_eng', models.CharField(blank=True, max_length=156)),
                ('short_descriptions_eng', models.CharField(blank=True, max_length=256)),
            ],
        ),
    ]
