# Generated by Django 4.2.4 on 2023-09-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asosiy_Sahifa', '0009_whyastruminfo2'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurMentors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=156)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('who_is_the_mentor', models.CharField(blank=True, max_length=156)),
                ('name_ru', models.CharField(blank=True, max_length=156)),
                ('title_ru', models.CharField(blank=True, max_length=500)),
                ('who_is_the_mentor_ru', models.CharField(blank=True, max_length=156)),
                ('name_eng', models.CharField(blank=True, max_length=156)),
                ('title_eng', models.CharField(blank=True, max_length=500)),
                ('who_is_the_mentor_eng', models.CharField(blank=True, max_length=156)),
            ],
        ),
    ]
