# Generated by Django 4.2.4 on 2023-09-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asosiy_Sahifa', '0010_ourmentors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=156)),
                ('image', models.ImageField(upload_to='')),
                ('name_lasname', models.CharField(blank=True, max_length=256)),
                ('skill', models.CharField(blank=True, max_length=156)),
                ('title_ru', models.CharField(blank=True, max_length=156)),
                ('image_ru', models.ImageField(upload_to='')),
                ('name_lasname_ru', models.CharField(blank=True, max_length=256)),
                ('skill_ru', models.CharField(blank=True, max_length=156)),
                ('title_eng', models.CharField(blank=True, max_length=156)),
                ('image_eng', models.ImageField(upload_to='')),
                ('name_lasname_eng', models.CharField(blank=True, max_length=256)),
                ('skill_eng', models.CharField(blank=True, max_length=156)),
            ],
        ),
    ]
