# Generated by Django 4.2.4 on 2023-09-09 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Asosiy_Sahifa', '0011_mentors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentors',
            name='image',
        ),
        migrations.RemoveField(
            model_name='mentors',
            name='image_eng',
        ),
        migrations.RemoveField(
            model_name='mentors',
            name='image_ru',
        ),
    ]
