# Generated by Django 4.2.4 on 2023-09-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asosiy_Sahifa', '0013_mentors_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locatsia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=156)),
                ('title', models.CharField(blank=True, max_length=156)),
                ('short_titile', models.CharField(blank=True, max_length=256)),
                ('name_ru', models.CharField(max_length=156)),
                ('title_ru', models.CharField(blank=True, max_length=156)),
                ('short_titile_ru', models.CharField(blank=True, max_length=256)),
                ('name_eng', models.CharField(blank=True, max_length=156)),
                ('title_eng', models.CharField(max_length=156)),
                ('short_titile_eng', models.CharField(blank=True, max_length=256)),
            ],
        ),
    ]
