# Generated by Django 4.2.4 on 2023-09-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asosiy_Sahifa', '0014_locatsia'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocatsiaInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=156)),
                ('tarif', models.CharField(blank=True, max_length=256)),
                ('title_ru', models.CharField(blank=True, max_length=156)),
                ('tarif_ru', models.CharField(blank=True, max_length=256)),
                ('title_eng', models.CharField(blank=True, max_length=156)),
                ('tarif_eng', models.CharField(blank=True, max_length=256)),
            ],
        ),
    ]
