# Generated by Django 4.2.4 on 2023-09-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asosiy_Sahifa', '0015_locatsiainfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='locatsiainfo',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
