# Generated by Django 4.2.5 on 2023-10-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asosiy_Sahifa', '0018_theles'),
    ]

    operations = [
        migrations.AddField(
            model_name='theles',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
