# Generated by Django 4.2.5 on 2023-10-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asosiy_Sahifa', '0019_theles_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='theles',
            name='name_eng',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='theles',
            name='name_ru',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='theles',
            name='short_descriptions_eng',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theles',
            name='short_descriptions_ru',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theles',
            name='title_eng',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='theles',
            name='title_ru',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='theles',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='theles',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
