# Generated by Django 4.2.2 on 2023-10-06 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asosiy_Sahifa', '0021_alter_theles_name_eng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsheader',
            name='title_right',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='newsheader',
            name='title_right_eng',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='newsheader',
            name='title_right_ru',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
