# Generated by Django 4.2.5 on 2023-09-11 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kurs_ichi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kurslaruchundarslar',
            name='title',
        ),
        migrations.RemoveField(
            model_name='kurslaruchundarslar',
            name='title_eng',
        ),
        migrations.RemoveField(
            model_name='kurslaruchundarslar',
            name='title_ru',
        ),
    ]
