# Generated by Django 4.2.5 on 2023-09-11 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kurs_ichi', '0002_remove_kurslaruchundarslar_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KoribChiqish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=250)),
                ('descriptions', models.CharField(max_length=500)),
                ('title_ru', models.CharField(max_length=100)),
                ('name_ru', models.CharField(max_length=250)),
                ('descriptions_ru', models.CharField(max_length=500)),
                ('title_eng', models.CharField(max_length=100)),
                ('name_eng', models.CharField(max_length=250)),
                ('descriptions_eng', models.CharField(max_length=500)),
                ('image', models.IntegerField(blank=True)),
            ],
        ),
    ]
