# Generated by Django 4.2.5 on 2023-09-11 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kurs_ichi', '0003_koribchiqish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='koribchiqish',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
