# Generated by Django 4.2.5 on 2023-09-11 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kurs_ichi', '0006_remove_bitiruvchilarvideolar_video_eng_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_lastname', models.CharField(max_length=156)),
                ('skill', models.CharField(max_length=256)),
                ('descriptions', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('name_lastname_ru', models.CharField(max_length=156)),
                ('skill_ru', models.CharField(max_length=256)),
                ('descriptions_ru', models.CharField(max_length=500)),
                ('name_lastname_eng', models.CharField(max_length=156)),
                ('skill_eng', models.CharField(max_length=256)),
                ('descriptions_eng', models.CharField(max_length=500)),
            ],
        ),
    ]
