# Generated by Django 4.2.5 on 2023-09-11 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kurs_ichi', '0007_comentarya'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='narxlar',
            name='title',
        ),
        migrations.RemoveField(
            model_name='narxlar',
            name='title_eng',
        ),
        migrations.RemoveField(
            model_name='narxlar',
            name='title_ru',
        ),
    ]
