# Generated by Django 4.2.5 on 2023-09-11 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kurs_ichi', '0008_remove_narxlar_title_remove_narxlar_title_eng_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kursjadvali',
            name='title',
        ),
        migrations.RemoveField(
            model_name='kursjadvali',
            name='title_eng',
        ),
        migrations.RemoveField(
            model_name='kursjadvali',
            name='title_ru',
        ),
    ]
