# Generated by Django 4.2.5 on 2023-09-11 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kurs_ichi', '0009_remove_kursjadvali_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savollar',
            name='title',
        ),
        migrations.RemoveField(
            model_name='savollar',
            name='title_eng',
        ),
        migrations.RemoveField(
            model_name='savollar',
            name='title_ru',
        ),
    ]
