# Generated by Django 4.2.4 on 2023-09-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kurs_ichi', '0010_remove_savollar_title_remove_savollar_title_eng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='koribchiqish',
            name='image',
            field=models.FileField(blank=True, upload_to='kurs_ichi/'),
        ),
    ]
