# Generated by Django 4.2.5 on 2023-09-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kurs_ichi', '0011_alter_koribchiqish_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Savollar1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=200)),
                ('descriptions1', models.CharField(max_length=1000)),
                ('title2', models.CharField(max_length=200)),
                ('descriptions2', models.CharField(max_length=1000)),
                ('title3', models.CharField(max_length=200)),
                ('descriptions3', models.CharField(max_length=1000)),
                ('title1_ru', models.CharField(max_length=200)),
                ('descriptions1_ru', models.CharField(max_length=1000)),
                ('title2_ru', models.CharField(max_length=200)),
                ('descriptions2_ru', models.CharField(max_length=1000)),
                ('_ru', models.CharField(max_length=200)),
                ('descriptions3_ru', models.CharField(max_length=1000)),
                ('title1_eng', models.CharField(max_length=200)),
                ('descriptions1_eng', models.CharField(max_length=1000)),
                ('title2_eng', models.CharField(max_length=200)),
                ('descriptions2_eng', models.CharField(max_length=1000)),
                ('title3_eng', models.CharField(max_length=200)),
                ('descriptions3_eng', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='SavollarJavob2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('descriptions', models.CharField(max_length=1000)),
                ('title_ru', models.CharField(max_length=200)),
                ('descriptions_ru', models.CharField(max_length=1000)),
                ('title_eng', models.CharField(max_length=200)),
                ('descriptions_eng', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RenameModel(
            old_name='Savollar',
            new_name='Savollar2',
        ),
        migrations.RenameModel(
            old_name='SavollarJavob',
            new_name='SavollarJavob1',
        ),
    ]
