# Generated by Django 4.2.5 on 2023-09-13 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kurs_ichi', '0012_savollar1_savollarjavob2_rename_savollar_savollar2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savollar1',
            old_name='_ru',
            new_name='title3_ru',
        ),
    ]
