# Generated by Django 4.2.3 on 2023-09-17 11:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kurs_ichi', '0013_rename__ru_savollar1_title3_ru'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='koribchiqish',
            name='image',
        ),
        migrations.AddField(
            model_name='koribchiqish',
            name='video',
            field=models.FileField(null=True, upload_to='videos_uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
