# Generated by Django 4.2.6 on 2023-10-23 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kurs_ichi', '0015_alter_koribchiqish_descriptions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savollar1',
            options={'verbose_name': 'Учебные программы', 'verbose_name_plural': 'Учебная программа'},
        ),
    ]
