# Generated by Django 4.2.6 on 2023-10-23 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kurs_ichi', '0016_alter_savollar1_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savollar1',
            options={'verbose_name': 'Учебная программа', 'verbose_name_plural': 'Учебные программы'},
        ),
    ]
