# Generated by Django 4.2.6 on 2023-10-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kurs_ichi', '0018_trainingprogram_questionandanswers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionandanswers',
            name='answer',
            field=models.TextField(),
        ),
    ]
