# Generated by Django 4.2.6 on 2023-10-23 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kurs_ichi', '0019_alter_questionandanswers_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionandanswers',
            name='training_program',
        ),
        migrations.RemoveField(
            model_name='trainingprogram',
            name='about_season_en',
        ),
        migrations.AddField(
            model_name='questionandanswers',
            name='answer_en',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionandanswers',
            name='answer_ru',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionandanswers',
            name='question_en',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionandanswers',
            name='question_ru',
            field=models.CharField(default='test', max_length=400),
        ),
        migrations.CreateModel(
            name='CourseSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('title_ru', models.CharField(max_length=200)),
                ('description_ru', models.TextField()),
                ('title_en', models.CharField(max_length=200)),
                ('description_en', models.TextField()),
                ('course_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_seasons', to='Kurs_ichi.trainingprogram')),
            ],
            options={
                'verbose_name': 'Сезон курса',
                'verbose_name_plural': 'Сезоны курса',
            },
        ),
        migrations.AddField(
            model_name='questionandanswers',
            name='course_season',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='question_and_answers', to='Kurs_ichi.courseseason'),
            preserve_default=False,
        ),
    ]
