# Generated by Django 4.2.6 on 2023-10-23 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kurs_ichi', '0020_remove_questionandanswers_training_program_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingprogram',
            name='about_season',
        ),
        migrations.RemoveField(
            model_name='trainingprogram',
            name='about_season_ru',
        ),
    ]
