# Generated by Django 4.2.6 on 2023-10-25 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cours', '0006_courses_is_main'),
        ('Kurs_ichi', '0022_delete_savollar1_delete_savollar2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treningdasturi',
            options={'verbose_name': 'Важность курса', 'verbose_name_plural': 'Важность курсов'},
        ),
        migrations.AddField(
            model_name='treningdasturi',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_importance', to='Cours.courses'),
        ),
    ]
