# Generated by Django 4.2.6 on 2023-10-25 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kurs_ichi', '0023_alter_treningdasturi_options_treningdasturi_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='treningdasturianswer',
            name='course_training',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_answers', to='Kurs_ichi.treningdasturi'),
        ),
    ]
