# Generated by Django 4.2.6 on 2023-10-25 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kurs_ichi', '0024_treningdasturianswer_course_training'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treningdasturianswer',
            options={'verbose_name': 'Oтвет на важность курса', 'verbose_name_plural': 'Ответы на важность курсов'},
        ),
    ]
