# Generated by Django 4.2.6 on 2023-10-28 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cours', '0006_courses_is_main'),
        ('Kurs_ichi', '0025_alter_treningdasturianswer_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('job_title', models.CharField(max_length=200)),
                ('job_type', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('full_name_ru', models.CharField(max_length=200)),
                ('job_title_ru', models.CharField(max_length=200)),
                ('job_type_ru', models.CharField(max_length=200)),
                ('description_ru', models.TextField()),
                ('full_name_en', models.CharField(max_length=200)),
                ('job_title_en', models.CharField(max_length=200)),
                ('job_type_en', models.CharField(max_length=200)),
                ('description_en', models.TextField()),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentors', to='Cours.courses')),
            ],
            options={
                'verbose_name': 'Mентор',
                'verbose_name_plural': 'Mенторы',
            },
        ),
    ]
