# Generated by Django 4.2.6 on 2023-10-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kurs_ichi', '0026_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='image',
            field=models.ImageField(null=True, upload_to='mentors/'),
        ),
    ]
