# Generated by Django 4.2.6 on 2023-10-28 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cours', '0006_courses_is_main'),
        ('Kurs_ichi', '0027_mentor_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mentor',
            new_name='AstrumMentor',
        ),
    ]
