# Generated by Django 4.2.3 on 2023-09-11 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Akademiya_Haqida', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='akademyahaqidaheader',
            name='image1_eng',
        ),
        migrations.RemoveField(
            model_name='akademyahaqidaheader',
            name='image1_ru',
        ),
        migrations.RemoveField(
            model_name='akademyahaqidaheader',
            name='image2_eng',
        ),
        migrations.RemoveField(
            model_name='akademyahaqidaheader',
            name='image2_ru',
        ),
        migrations.RemoveField(
            model_name='akademyahaqidaheader',
            name='image3_eng',
        ),
        migrations.RemoveField(
            model_name='akademyahaqidaheader',
            name='image3_ru',
        ),
        migrations.RemoveField(
            model_name='akademyahaqidaheader',
            name='image4_eng',
        ),
        migrations.RemoveField(
            model_name='akademyahaqidaheader',
            name='image4_ru',
        ),
        migrations.RemoveField(
            model_name='akademyahaqidaheader',
            name='image5_eng',
        ),
        migrations.RemoveField(
            model_name='akademyahaqidaheader',
            name='image5_ru',
        ),
        migrations.RemoveField(
            model_name='akademyahaqidaheader',
            name='image6_eng',
        ),
        migrations.RemoveField(
            model_name='akademyahaqidaheader',
            name='image6_ru',
        ),
        migrations.RemoveField(
            model_name='akademyahaqidaheader',
            name='image7_eng',
        ),
        migrations.RemoveField(
            model_name='akademyahaqidaheader',
            name='image7_ru',
        ),
    ]
