# Generated by Django 4.2.3 on 2023-09-11 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Akademiya_Haqida', '0002_remove_akademyahaqidaheader_image1_eng_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assideakademiyahaqida',
            name='image_eng',
        ),
        migrations.RemoveField(
            model_name='assideakademiyahaqida',
            name='image_ru',
        ),
        migrations.RemoveField(
            model_name='assidekurslar',
            name='image_eng',
        ),
        migrations.RemoveField(
            model_name='assidekurslar',
            name='image_ru',
        ),
        migrations.RemoveField(
            model_name='assidemashgulotkurslari',
            name='image_eng',
        ),
        migrations.RemoveField(
            model_name='assidemashgulotkurslari',
            name='image_ru',
        ),
        migrations.RemoveField(
            model_name='assidequlaylik',
            name='image_eng',
        ),
        migrations.RemoveField(
            model_name='assidequlaylik',
            name='image_ru',
        ),
        migrations.RemoveField(
            model_name='assidetalimtizimi',
            name='descriptions_eng',
        ),
        migrations.RemoveField(
            model_name='assidetalimtizimi',
            name='image1_eng',
        ),
        migrations.RemoveField(
            model_name='assidetalimtizimi',
            name='image1_ru',
        ),
        migrations.RemoveField(
            model_name='assidetalimtizimi',
            name='image2_eng',
        ),
        migrations.RemoveField(
            model_name='assidetalimtizimi',
            name='image2_ru',
        ),
        migrations.RemoveField(
            model_name='assidetalimtizimi',
            name='image3_eng',
        ),
        migrations.RemoveField(
            model_name='assidetalimtizimi',
            name='image3_ru',
        ),
        migrations.RemoveField(
            model_name='assidetalimtizimi',
            name='image4_eng',
        ),
        migrations.RemoveField(
            model_name='assidetalimtizimi',
            name='image4_ru',
        ),
        migrations.RemoveField(
            model_name='assidetalimtizimi',
            name='image5_eng',
        ),
        migrations.RemoveField(
            model_name='assidetalimtizimi',
            name='image5_ru',
        ),
        migrations.RemoveField(
            model_name='assidetalimtizimi',
            name='image6_eng',
        ),
        migrations.RemoveField(
            model_name='assidetalimtizimi',
            name='image6_ru',
        ),
        migrations.RemoveField(
            model_name='assidetalimtizimi',
            name='image7_eng',
        ),
        migrations.RemoveField(
            model_name='assidetalimtizimi',
            name='image7_ru',
        ),
    ]
