# Generated by Django 4.2.4 on 2023-09-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('data', models.CharField(blank=True, max_length=156)),
                ('short_descriptions', models.CharField(blank=True, max_length=256)),
                ('short_descriptions_big', models.CharField(blank=True, max_length=500)),
                ('duration', models.CharField(blank=True, max_length=256)),
                ('title_ru', models.CharField(blank=True, max_length=20)),
                ('image_ru', models.ImageField(blank=True, upload_to='')),
                ('data_ru', models.CharField(blank=True, max_length=156)),
                ('short_descriptions_ru', models.CharField(blank=True, max_length=256)),
                ('short_descriptions_big_ru', models.CharField(blank=True, max_length=500)),
                ('duration_ru', models.CharField(blank=True, max_length=256)),
                ('title_eng', models.CharField(blank=True, max_length=20)),
                ('image_eng', models.ImageField(blank=True, upload_to='')),
                ('data_eng', models.CharField(blank=True, max_length=156)),
                ('short_descriptions_eng', models.CharField(blank=True, max_length=256)),
                ('short_descriptions_big_eng', models.CharField(blank=True, max_length=500)),
                ('duration_eng', models.CharField(blank=True, max_length=256)),
            ],
        ),
    ]
