# Generated by Django 4.2.4 on 2023-09-09 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cours', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='image_eng',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='image_ru',
        ),
    ]
