# Generated by Django 4.2.3 on 2023-09-11 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cours', '0002_remove_courses_image_eng_remove_courses_image_ru'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kurslar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('title_ru', models.CharField(blank=True, max_length=250)),
                ('image_ru', models.ImageField(blank=True, upload_to='')),
                ('title_eng', models.CharField(blank=True, max_length=250)),
                ('image_eng', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
