# Generated by Django 4.2.3 on 2023-09-11 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cours', '0003_kurslar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kurslar',
            name='image_eng',
        ),
        migrations.RemoveField(
            model_name='kurslar',
            name='image_ru',
        ),
    ]
