# Generated by Django 4.2.2 on 2023-10-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cours', '0005_remove_kurslar_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
