from django.db import models


# Create your models here.

class Photo(models.Model):
    title = models.CharField(max_length=250, blank=True)

    title_ru = models.CharField(max_length=250, blank=True)

    title_eng = models.CharField(max_length=250, blank=True)

    def __str__(self):
        return self.title


class KompleksJoylashmalar(models.Model):
    title1 = models.CharField(max_length=100)
    title2 = models.CharField(max_length=100)
    title3 = models.CharField(max_length=100)
    title4 = models.CharField(max_length=100)
    title5 = models.CharField(max_length=100)
    title6 = models.CharField(max_length=100)
    title7 = models.CharField(max_length=100)
    title8 = models.CharField(max_length=100)
    title9 = models.CharField(max_length=100)
    title10 = models.CharField(max_length=100)
    title11 = models.CharField(max_length=100)
    title12 = models.CharField(max_length=100)
    title13 = models.CharField(max_length=100)
    title14 = models.CharField(max_length=100)
    title15 = models.CharField(max_length=100)
    title16 = models.CharField(max_length=100)
    title17 = models.CharField(max_length=100)
    title18 = models.CharField(max_length=100)
    title19 = models.CharField(max_length=100)
    title20 = models.CharField(max_length=100)

    title1_ru = models.CharField(max_length=100)
    title2_ru = models.CharField(max_length=100)
    title3_ru = models.CharField(max_length=100)
    title4_ru = models.CharField(max_length=100)
    title5_ru = models.CharField(max_length=100)
    title6_ru = models.CharField(max_length=100)
    title7_ru = models.CharField(max_length=100)
    title8_ru = models.CharField(max_length=100)
    title9_ru = models.CharField(max_length=100)
    title10_ru = models.CharField(max_length=100)
    title11_ru = models.CharField(max_length=100)
    title12_ru = models.CharField(max_length=100)
    title13_ru = models.CharField(max_length=100)
    title14_ru = models.CharField(max_length=100)
    title15_ru = models.CharField(max_length=100)
    title16_ru = models.CharField(max_length=100)
    title17_ru = models.CharField(max_length=100)
    title18_ru = models.CharField(max_length=100)
    title19_ru = models.CharField(max_length=100)
    title20_ru = models.CharField(max_length=100)

    title1_eng = models.CharField(max_length=100)
    title2_eng = models.CharField(max_length=100)
    title3_eng = models.CharField(max_length=100)
    title4_eng = models.CharField(max_length=100)
    title5_eng = models.CharField(max_length=100)
    title6_eng = models.CharField(max_length=100)
    title7_eng = models.CharField(max_length=100)
    title8_eng = models.CharField(max_length=100)
    title9_eng = models.CharField(max_length=100)
    title10_eng = models.CharField(max_length=100)
    title11_eng = models.CharField(max_length=100)
    title12_eng = models.CharField(max_length=100)
    title13_eng = models.CharField(max_length=100)
    title14_eng = models.CharField(max_length=100)
    title15_eng = models.CharField(max_length=100)
    title16_eng = models.CharField(max_length=100)
    title17_eng = models.CharField(max_length=100)
    title18_eng = models.CharField(max_length=100)
    title19_eng = models.CharField(max_length=100)
    title20_eng = models.CharField(max_length=100)

    image = models.ImageField(upload_to='photo/')
    image1 = models.ImageField(upload_to='photo/')
    image2 = models.ImageField(upload_to='photo/')
    image3 = models.ImageField(upload_to='photo/')
    image4 = models.ImageField(upload_to='photo/')
    image5 = models.ImageField(upload_to='photo/', blank=True)
    image6 = models.ImageField(upload_to='photo/', blank=True)
    image7 = models.ImageField(upload_to='photo/', blank=True)
    image8 = models.ImageField(upload_to='photo/', blank=True)
    image9 = models.ImageField(upload_to='photo/', blank=True)
    image10 = models.ImageField(upload_to='photo/', blank=True)
    image11 = models.ImageField(upload_to='photo/', blank=True)
    image12 = models.ImageField(upload_to='photo/', blank=True)
    image13 = models.ImageField(upload_to='photo/', blank=True)
    image14 = models.ImageField(upload_to='photo/', blank=True)
    image15 = models.ImageField(upload_to='photo/', blank=True)
    image16 = models.ImageField(upload_to='photo/', blank=True)
    image17 = models.ImageField(upload_to='photo/', blank=True)
    image18 = models.ImageField(upload_to='photo/', blank=True)
    image19 = models.ImageField(upload_to='photo/', blank=True)
    image20 = models.ImageField(upload_to='photo/', blank=True)

    def __str__(self):
        return self.title1


class BizningKurslarimiz(models.Model):
    title1 = models.CharField(max_length=100)
    title2 = models.CharField(max_length=100)
    title3 = models.CharField(max_length=100)
    title4 = models.CharField(max_length=100)
    title5 = models.CharField(max_length=100)
    title6 = models.CharField(max_length=100)
    title7 = models.CharField(max_length=100)
    title8 = models.CharField(max_length=100)
    title9 = models.CharField(max_length=100)
    title10 = models.CharField(max_length=100)
    title11 = models.CharField(max_length=100)
    title12 = models.CharField(max_length=100)
    title13 = models.CharField(max_length=100)
    title14 = models.CharField(max_length=100)
    title15 = models.CharField(max_length=100)
    title16 = models.CharField(max_length=100)
    title17 = models.CharField(max_length=100)
    title18 = models.CharField(max_length=100)
    title19 = models.CharField(max_length=100)
    title20 = models.CharField(max_length=100)

    title1_ru = models.CharField(max_length=100)
    title2_ru = models.CharField(max_length=100)
    title3_ru = models.CharField(max_length=100)
    title4_ru = models.CharField(max_length=100)
    title5_ru = models.CharField(max_length=100)
    title6_ru = models.CharField(max_length=100)
    title7_ru = models.CharField(max_length=100)
    title8_ru = models.CharField(max_length=100)
    title9_ru = models.CharField(max_length=100)
    title10_ru = models.CharField(max_length=100)
    title11_ru = models.CharField(max_length=100)
    title12_ru = models.CharField(max_length=100)
    title13_ru = models.CharField(max_length=100)
    title14_ru = models.CharField(max_length=100)
    title15_ru = models.CharField(max_length=100)
    title16_ru = models.CharField(max_length=100)
    title17_ru = models.CharField(max_length=100)
    title18_ru = models.CharField(max_length=100)
    title19_ru = models.CharField(max_length=100)
    title20_ru = models.CharField(max_length=100)

    title1_eng = models.CharField(max_length=100)
    title2_eng = models.CharField(max_length=100)
    title3_eng = models.CharField(max_length=100)
    title4_eng = models.CharField(max_length=100)
    title5_eng = models.CharField(max_length=100)
    title6_eng = models.CharField(max_length=100)
    title7_eng = models.CharField(max_length=100)
    title8_eng = models.CharField(max_length=100)
    title9_eng = models.CharField(max_length=100)
    title10_eng = models.CharField(max_length=100)
    title11_eng = models.CharField(max_length=100)
    title12_eng = models.CharField(max_length=100)
    title13_eng = models.CharField(max_length=100)
    title14_eng = models.CharField(max_length=100)
    title15_eng = models.CharField(max_length=100)
    title16_eng = models.CharField(max_length=100)
    title17_eng = models.CharField(max_length=100)
    title18_eng = models.CharField(max_length=100)
    title19_eng = models.CharField(max_length=100)
    title20_eng = models.CharField(max_length=100)

    image = models.ImageField(upload_to='photo/')
    image1 = models.ImageField(upload_to='photo/')
    image2 = models.ImageField(upload_to='photo/')
    image3 = models.ImageField(upload_to='photo/')
    image4 = models.ImageField(upload_to='photo/')
    image5 = models.ImageField(upload_to='photo/', blank=True)
    image6 = models.ImageField(upload_to='photo/', blank=True)
    image7 = models.ImageField(upload_to='photo/', blank=True)
    image8 = models.ImageField(upload_to='photo/', blank=True)
    image9 = models.ImageField(upload_to='photo/', blank=True)
    image10 = models.ImageField(upload_to='photo/', blank=True)
    image11 = models.ImageField(upload_to='photo/', blank=True)
    image12 = models.ImageField(upload_to='photo/', blank=True)
    image13 = models.ImageField(upload_to='photo/', blank=True)
    image14 = models.ImageField(upload_to='photo/', blank=True)
    image15 = models.ImageField(upload_to='photo/', blank=True)
    image16 = models.ImageField(upload_to='photo/', blank=True)
    image17 = models.ImageField(upload_to='photo/', blank=True)
    image18 = models.ImageField(upload_to='photo/', blank=True)
    image19 = models.ImageField(upload_to='photo/', blank=True)
    image20 = models.ImageField(upload_to='photo/', blank=True)

    def __str__(self):
        return self.title1


class KompanyaIchidagiHayot(models.Model):
    title1 = models.CharField(max_length=100)
    title2 = models.CharField(max_length=100)
    title3 = models.CharField(max_length=100)
    title4 = models.CharField(max_length=100)
    title5 = models.CharField(max_length=100)
    title6 = models.CharField(max_length=100)
    title7 = models.CharField(max_length=100)
    title8 = models.CharField(max_length=100)
    title9 = models.CharField(max_length=100)
    title10 = models.CharField(max_length=100)
    title11 = models.CharField(max_length=100)
    title12 = models.CharField(max_length=100)
    title13 = models.CharField(max_length=100)
    title14 = models.CharField(max_length=100)
    title15 = models.CharField(max_length=100)
    title16 = models.CharField(max_length=100)
    title17 = models.CharField(max_length=100)
    title18 = models.CharField(max_length=100)
    title19 = models.CharField(max_length=100)
    title20 = models.CharField(max_length=100)

    title1_ru = models.CharField(max_length=100)
    title2_ru = models.CharField(max_length=100)
    title3_ru = models.CharField(max_length=100)
    title4_ru = models.CharField(max_length=100)
    title5_ru = models.CharField(max_length=100)
    title6_ru = models.CharField(max_length=100)
    title7_ru = models.CharField(max_length=100)
    title8_ru = models.CharField(max_length=100)
    title9_ru = models.CharField(max_length=100)
    title10_ru = models.CharField(max_length=100)
    title11_ru = models.CharField(max_length=100)
    title12_ru = models.CharField(max_length=100)
    title13_ru = models.CharField(max_length=100)
    title14_ru = models.CharField(max_length=100)
    title15_ru = models.CharField(max_length=100)
    title16_ru = models.CharField(max_length=100)
    title17_ru = models.CharField(max_length=100)
    title18_ru = models.CharField(max_length=100)
    title19_ru = models.CharField(max_length=100)
    title20_ru = models.CharField(max_length=100)

    title1_eng = models.CharField(max_length=100)
    title2_eng = models.CharField(max_length=100)
    title3_eng = models.CharField(max_length=100)
    title4_eng = models.CharField(max_length=100)
    title5_eng = models.CharField(max_length=100)
    title6_eng = models.CharField(max_length=100)
    title7_eng = models.CharField(max_length=100)
    title8_eng = models.CharField(max_length=100)
    title9_eng = models.CharField(max_length=100)
    title10_eng = models.CharField(max_length=100)
    title11_eng = models.CharField(max_length=100)
    title12_eng = models.CharField(max_length=100)
    title13_eng = models.CharField(max_length=100)
    title14_eng = models.CharField(max_length=100)
    title15_eng = models.CharField(max_length=100)
    title16_eng = models.CharField(max_length=100)
    title17_eng = models.CharField(max_length=100)
    title18_eng = models.CharField(max_length=100)
    title19_eng = models.CharField(max_length=100)
    title20_eng = models.CharField(max_length=100)

    image = models.ImageField(upload_to='photo/')
    image1 = models.ImageField(upload_to='photo/')
    image2 = models.ImageField(upload_to='photo/')
    image3 = models.ImageField(upload_to='photo/')
    image4 = models.ImageField(upload_to='photo/')
    image5 = models.ImageField(upload_to='photo/', blank=True)
    image6 = models.ImageField(upload_to='photo/', blank=True)
    image7 = models.ImageField(upload_to='photo/', blank=True)
    image8 = models.ImageField(upload_to='photo/', blank=True)
    image9 = models.ImageField(upload_to='photo/', blank=True)
    image10 = models.ImageField(upload_to='photo/', blank=True)
    image11 = models.ImageField(upload_to='photo/', blank=True)
    image12 = models.ImageField(upload_to='photo/', blank=True)
    image13 = models.ImageField(upload_to='photo/', blank=True)
    image14 = models.ImageField(upload_to='photo/', blank=True)
    image15 = models.ImageField(upload_to='photo/', blank=True)
    image16 = models.ImageField(upload_to='photo/', blank=True)
    image17 = models.ImageField(upload_to='photo/', blank=True)
    image18 = models.ImageField(upload_to='photo/', blank=True)
    image19 = models.ImageField(upload_to='photo/', blank=True)
    image20 = models.ImageField(upload_to='photo/', blank=True)

    def __str__(self):
        return self.title1
