# Generated by Django 4.2.5 on 2023-09-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Karyera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250)),
                ('short_descriptions', models.CharField(blank=True, max_length=500)),
                ('title_ru', models.CharField(blank=True, max_length=250)),
                ('short_descriptions_ru', models.CharField(blank=True, max_length=500)),
                ('title_eng', models.CharField(blank=True, max_length=250)),
                ('short_descriptions_eng', models.CharField(blank=True, max_length=500)),
                ('img1', models.ImageField(upload_to='about_us/')),
                ('img2', models.ImageField(upload_to='about_us/')),
                ('img3', models.ImageField(upload_to='about_us/')),
                ('img4', models.ImageField(upload_to='about_us/')),
                ('img5', models.ImageField(upload_to='about_us/')),
                ('img6', models.ImageField(upload_to='about_us/')),
            ],
        ),
        migrations.CreateModel(
            name='Vakansiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(blank=True, max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('occupation', models.CharField(blank=True, max_length=250)),
                ('short_descriptions', models.CharField(blank=True, max_length=256)),
                ('prise', models.CharField(blank=True, max_length=100)),
                ('button_text', models.CharField(blank=True, max_length=20)),
                ('data_ru', models.CharField(blank=True, max_length=20)),
                ('occupation_ru', models.CharField(blank=True, max_length=250)),
                ('short_descriptions_ru', models.CharField(blank=True, max_length=256)),
                ('prise_ru', models.CharField(blank=True, max_length=100)),
                ('button_text_ru', models.CharField(blank=True, max_length=20)),
                ('data_eng', models.CharField(blank=True, max_length=20)),
                ('occupation_eng', models.CharField(blank=True, max_length=250)),
                ('short_descriptions_eng', models.CharField(blank=True, max_length=256)),
                ('prise_eng', models.CharField(blank=True, max_length=100)),
                ('button_text_eng', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
