# Generated by Django 4.2.5 on 2023-09-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biz_haqimizda', '0002_alter_karyera_img1_alter_karyera_img2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=12)),
                ('img1', models.ImageField(blank=True, upload_to='about_us/')),
                ('img2', models.ImageField(blank=True, upload_to='about_us/')),
                ('img3', models.ImageField(blank=True, upload_to='about_us/')),
                ('img4', models.ImageField(blank=True, upload_to='about_us/')),
                ('img5', models.ImageField(blank=True, upload_to='about_us/')),
                ('img6', models.ImageField(blank=True, upload_to='about_us/')),
            ],
        ),
        migrations.RemoveField(
            model_name='karyera',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='karyera',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='karyera',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='karyera',
            name='img4',
        ),
        migrations.RemoveField(
            model_name='karyera',
            name='img5',
        ),
        migrations.RemoveField(
            model_name='karyera',
            name='img6',
        ),
    ]
