# Generated by Django 4.2.5 on 2023-09-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biz_haqimizda', '0003_photo_remove_karyera_img1_remove_karyera_img2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='img1',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
