# Generated by Django 4.2.5 on 2023-09-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biz_haqimizda', '0004_alter_photo_img1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='img1',
            field=models.ImageField(blank=True, upload_to='about_us/'),
        ),
    ]
