# Generated by Django 4.2.5 on 2023-09-11 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Biz_haqimizda', '0006_delete_photo_karyera_img1_karyera_img2_karyera_img3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='karyera',
            old_name='img1',
            new_name='image1',
        ),
        migrations.RenameField(
            model_name='karyera',
            old_name='img2',
            new_name='image2',
        ),
        migrations.RenameField(
            model_name='karyera',
            old_name='img3',
            new_name='image3',
        ),
        migrations.RenameField(
            model_name='karyera',
            old_name='img4',
            new_name='image4',
        ),
        migrations.RenameField(
            model_name='karyera',
            old_name='img5',
            new_name='image5',
        ),
        migrations.RemoveField(
            model_name='karyera',
            name='img6',
        ),
    ]
